name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag addressbook:$(date +%s)
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Tag the Docker image
      run: docker tag addressbook:$(date +%s) addressbook:latest     
    - name: Push the Docker image
      run: docker push addressbook:$(date +%s)
    - name: Log out from Docker Hub
      run: docker logout
    
